### ISSUE TITLE
in bkz2, get_pruning computes its own radius

### ISSUE THREAD

**Issue by lducas** [fplll/fpylll#84]
A radius is computed in svp_reduction, wouldn't it make sens to pass it to get_pruning ?

**Comment by lducas** [comment]
Also, we should use gaussian_heuristic rather than adjust_to_gh_bound when computing gh_radius ?

@malb I'm happy taking care of it if you agree.

**Comment by malb** [comment]
+1 for using `gaussian_heuristic` 
+1 for passing on radius

Actually, isn't there currently a bug when `BKZ.GH_BND` is set? `get_pruning` seems to select wrong pruning parameters in this case (?)

**Comment by lducas** [comment]
I've looked at it, and it actually seems more logical (and more efficient) to make get_pruning in charge of computing the radius for the main function. Indeed, decreasing radius to gh_bound is some form of pruning...
This is done in #b1c21e9

As the behaviour of the algorithm is changed a little bit, maybe we should run some regression check, both on performances and root hermite factor. @malb do you a recommended way to proceed with such checks ?

**Comment by malb** [comment]
I think @blowfish880 is the resident expert on convincing yourself that a change didn't make lattice reduction worse.

**Comment by blowfish880** [comment]
admittedly, my approach is pretty ad-hoc at this point. i usually sample a couple of lattices in dimension about 180 (q-ary, k=90, b=30 and intrel,b=1800) and run bkz (1 or 2 rounds) in different block sizes (around 45 to 80 since this is still doable in reasonable time) for both the master branch and the branch with the changes. running it in verbose will give you a pretty good idea on how well they are doing, both in running time (wall time and enumerated nodes) and output quality (length of first vector and slope). another thing i usually do is to compare the running time of test_bkz in the different branches.

as i said, this is pretty ad-hoc and a more systematic approach would be nice. but since a lot of these tests are pretty time consuming and running time depends on the system it is run on, this is tricky to do. might be worth opening its own ticket.

**Comment by lducas** [comment]
I did this kind of test, essentially progressive strategy: one tour of each block size on a lattice of dim 160. I observed slight improvement of both RHF and running time (maybe not so significant). I think it can be merged.

**Comment by lducas** [comment]
Closed by #89
